#!/bin/ksh
#
#@ output = nmm_out/out
#@ error = nmm_out/err
#@ job_type = parallel
#@ tasks_per_node = 8
#@ node = 2
#@ node_usage=shared
####@ blocking = unlimited
#@ resources=ConsumableCPUs(1)ConsumableMemory(500MB)
#@ class = debug
##@ class = dev
###@ group = devqpri
###@ group = devonprod
##@ wall_clock_limit = 01:00:00
#@ wall_clock_limit = 00:10:00
#@ preferences = Feature == "dev"
#@ network.MPI = csss,shared,us
#@ bulkxfer=yes
#@ account_no=NAM-T2O
#@ queue
#
#
set -x
#
### For MPI
#
##export BIND_TASKS=no
##export MP_EAGER_LIMIT=65536
export MP_SHARED_MEMORY=yes
##export MP_SINGLE_THREAD=yes
export MP_LABELIO=yes
export MP_STDOUTMODE=ordered
export MEMORY_AFFINITY=mcm
export MP_COREFILE_FORMAT=core.txt
export TARGET_CPU_RANGE="-1"
export XLSMPOPTS="parthds=2:stack=128000000"
export AIXTHREAD_SCOPE=S
export MALLOCMULTIHEAP=true


RUNDIR=/ptmp/${USER}/nmm.2 ### change here
DATADIR=/meso/noscrub/wx22tb/nmmb_input/input_global
SRCDIR=/meso/save/${USER}/trunk_nems   ##### change here

mkdir -p $RUNDIR
cd $RUNDIR
ls

echo $DATADIR
ls $DATADIR

cp $DATADIR/test_input_nmmb_global_257_181_35-2007091800 main_input_filename
#cp /meso/save/wx20rv/NEMS_new/NEMS_1.0_COLD/trunk/run/tmp/nmm_b_restart.004 restart_file
cp $SRCDIR/run/configfile_global_new $RUNDIR/configure_file

cp $DATADIR/tr* .

cp /nwprod/fix/nam_micro_lookup.dat ETAMPNEW_DATA
cp /meso/save/wx22tb/WRF_repository/run/RRT* .
cp /meso/noscrub/wx20rv/NOAH_wrf_data/*.TBL .

echo "Model started:  " `date`

poe hpmcount -o nmm.2.test /u/wx15ja/bin/hybrid_launch $SRCDIR/MAIN_NEMS.x

echo "Model ended:    " `date`

exit

