!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!     Bin sizes
!     ---------
      integer, parameter              :: NBIN_BCWT = 2 ! Black Carbon Wet Deposition 
      integer, parameter              :: NBIN_BCDP = 2 ! Black Carbon Dry Deposition 
      integer, parameter              :: NBIN_BCEM = 2 ! Black Carbon Emission 

!     Bin-indexed Chem Arrays
!     -----------------------
      type(Chem_Array), target        ::    BCWT(NBIN_BCWT) ! EXPORT: Black Carbon Wet Deposition 
      type(Chem_Array), pointer       :: ptrBCWT(:)  ! EXPORT: Black Carbon Wet Deposition 
      type(Chem_Array), target        ::    BCDP(NBIN_BCDP) ! EXPORT: Black Carbon Dry Deposition 
      type(Chem_Array), pointer       :: ptrBCDP(:)  ! EXPORT: Black Carbon Dry Deposition 
      type(Chem_Array), target        ::    BCEM(NBIN_BCEM) ! EXPORT: Black Carbon Emission 
      type(Chem_Array), pointer       :: ptrBCEM(:)  ! EXPORT: Black Carbon Emission 

!     Local array referencing the Import/Export states
!     ------------------------------------------------
      type(Chem_Array), target        ::    BCMASS ! EXPORT: Black Carbon Mass Mixing Ratio
      type(Chem_Array), pointer       :: ptrBCMASS ! EXPORT: Black Carbon Mass Mixing Ratio
      type(Chem_Array), target        ::    BCHYPHIL ! EXPORT: Black Carbon Hydrophobic to Hydrophilic
      type(Chem_Array), pointer       :: ptrBCHYPHIL ! EXPORT: Black Carbon Hydrophobic to Hydrophilic
      type(Chem_Array), target        ::    BCEMAN ! EXPORT: Black Carbon Anthropogenic Emissions
      type(Chem_Array), pointer       :: ptrBCEMAN ! EXPORT: Black Carbon Anthropogenic Emissions
      type(Chem_Array), target        ::    BCEMBB ! EXPORT: Black Carbon Biomass Burning Emissions
      type(Chem_Array), pointer       :: ptrBCEMBB ! EXPORT: Black Carbon Biomass Burning Emissions
      type(Chem_Array), target        ::    BCEMBF ! EXPORT: Black Carbon Biofuel Emissions
      type(Chem_Array), pointer       :: ptrBCEMBF ! EXPORT: Black Carbon Biofuel Emissions
      type(Chem_Array), target        ::    BCSMASS ! EXPORT: Black Carbon Surface Mass Concentration
      type(Chem_Array), pointer       :: ptrBCSMASS ! EXPORT: Black Carbon Surface Mass Concentration
      type(Chem_Array), target        ::    BCCMASS ! EXPORT: Black Carbon Column Mass Density
      type(Chem_Array), pointer       :: ptrBCCMASS ! EXPORT: Black Carbon Column Mass Density
      type(Chem_Array), target        ::    BCEXTTAU ! EXPORT: Black Carbon Extinction AOT [550 nm]
      type(Chem_Array), pointer       :: ptrBCEXTTAU ! EXPORT: Black Carbon Extinction AOT [550 nm]
      type(Chem_Array), target        ::    BCSCATAU ! EXPORT: Black Carbon Scattering AOT [550 nm]
      type(Chem_Array), pointer       :: ptrBCSCATAU ! EXPORT: Black Carbon Scattering AOT [550 nm]
