!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!     Bin sizes
!     ---------
      integer, parameter              :: NBIN_DUWT = 5 ! Dust Wet Deposition 
      integer, parameter              :: NBIN_DUEM = 5 ! Dust Emission 
      integer, parameter              :: NBIN_DUDP = 5 ! Dust Dry Deposition 
      integer, parameter              :: NBIN_DUSD = 5 ! Dust Sedimentation 

!     Bin-indexed Chem Arrays
!     -----------------------
      type(Chem_Array), target        ::    DUWT(NBIN_DUWT) ! EXPORT: Dust Wet Deposition 
      type(Chem_Array), pointer       :: ptrDUWT(:)  ! EXPORT: Dust Wet Deposition 
      type(Chem_Array), target        ::    DUEM(NBIN_DUEM) ! EXPORT: Dust Emission 
      type(Chem_Array), pointer       :: ptrDUEM(:)  ! EXPORT: Dust Emission 
      type(Chem_Array), target        ::    DUDP(NBIN_DUDP) ! EXPORT: Dust Dry Deposition 
      type(Chem_Array), pointer       :: ptrDUDP(:)  ! EXPORT: Dust Dry Deposition 
      type(Chem_Array), target        ::    DUSD(NBIN_DUSD) ! EXPORT: Dust Sedimentation 
      type(Chem_Array), pointer       :: ptrDUSD(:)  ! EXPORT: Dust Sedimentation 

!     Local array referencing the Import/Export states
!     ------------------------------------------------
      type(Chem_Array), target        ::    DUMASS ! EXPORT: Dust Mass Mixing Ratio
      type(Chem_Array), pointer       :: ptrDUMASS ! EXPORT: Dust Mass Mixing Ratio
      type(Chem_Array), target        ::    DUMASS25 ! EXPORT: Dust Mass Mixing Ratio - PM 2.5
      type(Chem_Array), pointer       :: ptrDUMASS25 ! EXPORT: Dust Mass Mixing Ratio - PM 2.5
      type(Chem_Array), target        ::    DUSMASS ! EXPORT: Dust Surface Mass Concentration
      type(Chem_Array), pointer       :: ptrDUSMASS ! EXPORT: Dust Surface Mass Concentration
      type(Chem_Array), target        ::    DUCMASS ! EXPORT: Dust Column Mass Density
      type(Chem_Array), pointer       :: ptrDUCMASS ! EXPORT: Dust Column Mass Density
      type(Chem_Array), target        ::    DUEXTTAU ! EXPORT: Dust Extinction AOT [550 nm]
      type(Chem_Array), pointer       :: ptrDUEXTTAU ! EXPORT: Dust Extinction AOT [550 nm]
      type(Chem_Array), target        ::    DUSCATAU ! EXPORT: Dust Scattering AOT [550 nm]
      type(Chem_Array), pointer       :: ptrDUSCATAU ! EXPORT: Dust Scattering AOT [550 nm]
      type(Chem_Array), target        ::    DUSMASS25 ! EXPORT: Dust Surface Mass Concentration - PM 2.5
      type(Chem_Array), pointer       :: ptrDUSMASS25 ! EXPORT: Dust Surface Mass Concentration - PM 2.5
      type(Chem_Array), target        ::    DUCMASS25 ! EXPORT: Dust Column Mass Density - PM 2.5
      type(Chem_Array), pointer       :: ptrDUCMASS25 ! EXPORT: Dust Column Mass Density - PM 2.5
      type(Chem_Array), target        ::    DUEXTT25 ! EXPORT: Dust Extinction AOT [550 nm] - PM 2.5
      type(Chem_Array), pointer       :: ptrDUEXTT25 ! EXPORT: Dust Extinction AOT [550 nm] - PM 2.5
      type(Chem_Array), target        ::    DUSCAT25 ! EXPORT: Dust Scattering AOT [550 nm] - PM 2.5
      type(Chem_Array), pointer       :: ptrDUSCAT25 ! EXPORT: Dust Scattering AOT [550 nm] - PM 2.5
      type(Chem_Array), target        ::    DUAERIDX ! EXPORT: Dust TOMS UV Aerosol Index
      type(Chem_Array), pointer       :: ptrDUAERIDX ! EXPORT: Dust TOMS UV Aerosol Index
