#!/bin/ksh
#
# @ job_name = _JOB_NAME1_
# @ job_type = _JOB_TYPE_
# @ account_no = _ACCT_NO_
# @ output = _OUTPUT_
# @ error = _ERROR_ 
# @ resources = ConsumableMemory(_CONSUMABLE_MEMORY_) ConsumableCpus(1)
# @ node_usage = _NODEUSAGE_
# @ tasks_per_node = _TASK_PER_NODE_
# @ node = _NODE_
# @ network.MPI=csss,shared,us
# @ bulkxfer = yes
# @ class = _CLASS_
# @ group = _GROUP_
# @ wall_clock_limit = _WALL_CLOCK_TIME_
# @ queue
#
set -x
#
 export CDATE=_CDATE_

# -------------------------------------------------------------
# SFCPRESS_ID=0 or 1 for ln(psfc), 2 for psfc
 export SFCPRESS_ID=_SFCPRESS_ID_
# THERMODYN_ID=3 for enthalphy, 0 or 1 for virtual T, 2 for T
 export THERMODYN_ID=_THERMODYN_ID_
 export hybrid=_HYBRID_
 export GEN_COORD_HYBRID=_GENCOORDHYBRID_
#***************************************************************
#                    N2 ,    H2O,     O3,        CLW,    O,      O2
#export RIlist="  296.8034, 461.50, 173.2247,    0.0,  519.674, 259.837 "
#export CPIlist=" 1039.645, 1846.0, 820.2391,    0.0, 1299.185, 918.0969"
#***************************************************************
#                   Dry ,    H2O,     O3,        CLW,    O,      O2
export CPIlist=" 1004.6,   1846.0, 820.2391,    0.0"
export RIlist="  286.05,   461.50, 173.2247,    0.0"
#***************************************************************
#
#    Set up horizontal and vertical resolution ; default will be T6264
#
 export wave=_WAVE_ ; export lm=_LM_ ; export lsoil=_LSOIL_
#
export NCP=cp
export FTSFS=0.0
export FAISS=0.0
#
#  This script is NOT complete for running multiple ensemble members
#
 export ENS_NUM=_ENS_NUM_
#
 tasks=_TASKS_  ; export PE1=_PE1_ 
#
export MP_STDOUTMODE=_MP_STDOUTMODE_
export MP_SHARED_MEMORY=_MP_SHARED_MEMORY_
export MEMORY_AFFINITY=_MEMORY_AFFINITY_
export NTHREADS=_THREADS1_
export XLSMPOPTS="parthds=$NTHREADS:spins=0:yields=0:stack=512000000"
export SPINLOOPTIME=_SPINLOOPTIME_
export YIELDLOOPTIME=_YIELDLOOPTIME_
export AIXTHREAD_SCOPE=_AIXTHREAD_SCOPE_
export MALLOCMULTIHEAP=_MALLOCMULTIHEAP_
#
#
#    Set up experiment and directory names
#
 export expt=_EXPERIMENT_NAME_
#
 export NSCDIR=_NSCDIR_
 export TOPDIR=_TOPDIR_
 export DUMPDIR=_DUMPDIR_
 export MP_COREFILE_FORMAT=_MP_COREFILE_FORMAT_ 
 export RUNDIR=_RUNDIR_
 export SCRIPTS=_SCRIPTS_

 export cold_sfc=_COLD_SFC_
#
#
#
# For two tracers
  export ntrc=_NTRC_  ; export varid=_VARID_ ; export numcld=_NUMCLD_
#
  export change_res=_CHANGE_RES_
#
  export ic_type=_IC_TYPE_
#
#    Forecast model : horizontal truncation  and vertical levels
#
#
export NTRAC=_NTRAC_
export NTOZ=_NTOZ_
export NTCW=_NTCW_
export NCLD=_NCLD_
export NMTVR=_NMTVR_
#
export lsm=_LSM_
#
export R=${wave}${lm}
echo $R
if [ $hybrid = YES ] ; then
 export SIGLEVEL=_SIGLEVEL1_
elif [ $GEN_COORD_HYBRID = YES ] ; then
  Apercent=${Apercent:-100}
  export SIGLEVEL=_SIGLEVEL2_
fi
#
export IDVM=_IDVM1_ ; export IDSL=_IDSL1_
if [ $hybrid = YES ] ; then
 export IDVC=_IDVC1_
 export nvcoord=_NVCOORD1_ ; export ivssfc=_IVSSFC1_
elif [ $GEN_COORD_HYBRID = YES ] ; then
 export IDVC=_IDVC2_ ; export IDSL=_IDSL2_ ; export ivssfc=_IVSSFC2_
 export IDVM=_IDVM2_
 export ivssig=_IVSSIG_ ; export nvcoord=_NVCOORD2_ ; export LATCH=_LATCH_
else
 export IDVC=_IDVC3_ ; export ivssfc=_IVSSFC3_
fi
#
# ***************************************************************
#    Below here no change needed most of the time
#    ____________________________________________
#
mkdir -p $RUNDIR
cd $RUNDIR
export COMOUT=$RUNDIR
#
export FIXGLOBAL=_FIXGLOBAL_
#
export kop=26
if [[ $lm -eq 64 ]] ; then
  export kop=46
fi
#
 export CHGRESDIR=_CHGRESDIR_
 export CHGRESEXEC=_CHGRESEXEC_
 export CHGRESSH=_CHGRESSH1_
#
export LANDICE_OPT=_LANDICE_OPT_
export CLIMO_FIELDS_OPT=_CLIMO_FIELDS_OPT_
#
# ----------------- determine resolution related ----------------------
#
if [[ $wave -eq 62 ]] ; then
  export LONF=192 ; export LATG=94 ; export LONR=192 ; export LATR=94
  export im=$LONR ; export jm=$LATR ; export iop=144 ; export jop=73
  if [[ $lm -eq 64 ]] ; then
    export DELTIM=${DELTIM:-900}
  fi
  if [[ $lm -eq 150 ]] ; then
    export DELTIM=${DELTIM:-180}
  fi
  export DELTIM=${DELTIM:-1200}
elif [[ $wave -eq 126 ]] ; then
  export LONF=384 ; export LATG=190 ; export LONR=384 ; export LATR=190
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-600}
elif [[ $wave -eq 170 ]] ; then
  export LONF=512 ; export LATG=256 ; export LONR=512 ; export LATR=256
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-450}
elif [[ $wave -eq 190 ]] ; then
  export LONF=576 ; export LATG=288 ; export LONR=576 ; export LATR=288
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-300}
elif [[ $wave -eq 254 ]] ; then
  export LONF=768 ; export LATG=384 ; export LONR=768 ; export LATR=384
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-300}
elif [[ $wave -eq 382 ]] ; then
  export LONF=1152 ; export LATG=576 ; export LONR=1152 ; export LATR=576
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-180}
elif [[ $wave -eq 510 ]] ; then
  export LONF=1536 ; export LATG=766 ; export LONR=1536 ; export LATR=766
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-120}
  export OROGRAPHY=_OROGRAPHY_
  export MTNVAR=_MTNVAR_
fi
#
# ------------------ initial data ---------------------------
#
  CDUMP=_CDUMP_
# For parallel or other initial conditions
  if [[ ${ic_type} = prx ]] ; then
    export datic=$DUMPDIR/$CDATE/$CDUMP
    export sig_fname=siganl.$CDUMP.$CDATE
    export sfc_fname=sfcanl.$CDUMP.$CDATE
  fi
#
# ----------------- change resolution or not ----------------
#
export JCAP=$wave
export LEVS=$lm
export LONB=$im
export LATB=$jm
export VERBOSE=YES
#

  export SIGINP=$datic/${sig_fname}
  export SFCINP=$datic/${sfc_fname}
  export GFSOUT=$RUNDIR/gfsanl.$CDATE
  export SIGOUT=$RUNDIR/siganl.$CDATE
  export SFCOUT=$RUNDIR/sfcanl.$CDATE
#
  echo ${change_res}
  if [[ ${change_res} = YES ]] ; then
    export CHGRESVARS=_CHGRESVARS1_
    export SIGLEVEL=_SIGLEVEL3_
    export LONSPERLAT=_LONSPERLAT_
    export CHGRESSH=_CHGRESSH2_
    export CHGRESVARS=_CHGRESVARS2_
    $CHGRESSH
  else
    ${NCP:-cp} $SIGINP $SIGOUT
    ${NCP:-cp} $SFCINP $SFCOUT
  fi
  export SIGI=$SIGOUT
  export GFSI=$GFSOUT
  export SFCI=$SFCOUT

