#!/bin/ksh
#
# @ job_name = _JOB_NAME_
# @ job_type = _JOB_TYPE_
# @ account_no = _ACCT_NO_
# @ output = _OUTPUT_
# @ error = _ERROR_
# @ resources = ConsumableMemory(_CONSUMABLE_MEMORY_) ConsumableCpus(1)
# @ node_usage = _NODEUSAGE_
# @ tasks_per_node = _TASK_PER_NODE_
# @ node = _NODE_
# @ network.MPI=csss,shared,us
# @ bulkxfer = yes
# @ class = _CLASS_
# @ group = _GROUP_
# @ wall_clock_limit = _WALL_CLOCK_TIME_
# @ queue
#
set -x
#
 export CDATE=_CDATE_


 export ADIAB=_ADIAB_
 export REDUCED_GRID=_REDUCED_GRID_

# SFCPRESS_ID=0 or 1 for ln(psfc), 2 for psfc
 export SFCPRESS_ID=_SFCPRESS_ID_
# THERMODYN_ID=3 for enthalphy, 0 or 1 for virtual T, 2 for T
 export THERMODYN_ID=_THERMODYN_ID_
#
 export IDVC=_IDVC_
 export hybrid=_HYBRID_
 export GEN_COORD_HYBRID=_GENCOORDHYBRID_
# SPECTRAL_LOOP       2 for old option, 1 is for one loop.
 export SPECTRAL_LOOP=_SPECTRAL_LOOP_
#***************************************************************
#                    N2 ,    H2O,     O3,        CLW,    O,      O2
#export CPIlist=" 1039.645, 1846.0, 820.2391,    0.0, 1299.185, 918.0969"
#export RIlist="  296.8034, 461.50, 173.2247,    0.0,  519.674, 259.837 "
#***************************************************************
#                   Dry ,    H2O,     O3,        CLW,    O,      O2
export CPIlist=" 1004.6,   1846.0, 820.2391,    0.0"
export RIlist="  286.05,   461.50, 173.2247,    0.0"
#***************************************************************
#
#    Set up horizontal and vertical resolution ; default will be T6264
#
 export wave=_WAVE_ ; export lm=_LM_ ; export lsoil=_LSOIL_
#
export NCP=cp
export FTSFS=0.0
export FAISS=0.0
#
#  This script is NOT complete for running multiple ensemble members
#
 export ENS_NUM=_ENS_NUM_
#
 tasks=_TASKS_  ; export PE1=_PE_ 
#
export MP_STDOUTMODE=_MP_STDOUTMODE_
export MP_SHARED_MEMORY=_MP_SHARED_MEMORY_
export MEMORY_AFFINITY=_MEMORY_AFFINITY_
export NTHREADS=_THREADS_
export XLSMPOPTS="parthds=$NTHREADS:spins=0:yields=0:stack=512000000"
export SPINLOOPTIME=_SPINLOOPTIME_
export YIELDLOOPTIME=_YIELDLOOPTIME_
export AIXTHREAD_SCOPE=_AIXTHREAD_SCOPE_
export MALLOCMULTIHEAP=_MALLOCMULTIHEAP_
#
 export FHROT=0
#
#    Set up experiment and directory names
#
 export expt=_EXPERIMENT_NAME_
#
 export NSCDIR=_NSCDIR_
 export TOPDIR=_TOPDIR_
 export DUMPDIR=_DUMPDIR_
 export MP_COREFILE_FORMAT=_MP_COREFILE_FORMAT_
 export RUNDIR=_RUNDIR_
 export SCRIPTS=_SCRIPTS_
 export fcst_begin=_FCSTBEGIN_
 export cold_sfc=_COLD_SFC_
#
#
#
#
#    nhourb is the beginig hour.  If nhourb=0, then initial condition
#    needs to be specified. ndays is the Length of #orecast in days
#    begining from nhourb
#
 export ndays=_NDAYS_
if [[ ${fcst_begin} = YES ]] ; then
 export nhourb=_NHOURSB1_
else
 if [[ -s $RUNDIR/sigr1$FM ]] ; then
   export nhourb=_NHOURSB2_
   export FHROT=${FHROT:-$nhourb}
 else
   nhourb=$((ndays*24))
 fi
fi
#
#
export nhours=`expr $ndays \* 24`

#
# For two tracers
  export ntrc=_NTRC_  ; export varid=_VARID_ ; export numcld=_NUMCLD_
#
#
 export fmax=$nhours
 export fout=_FOUT_  
 export fzer=_FZER_  
 export fcyc=_FCYC_ 
 export fdfi=_FDFI_ 
 export FHRES=$nhours
#
#    Forecast model : horizontal truncation  and vertical levels
#                     ---------------------
#
#
export NTRAC=_NTRAC_
export NTOZ=_NTOZ_
export NTCW=_NTCW_
export NCLD=_NCLD_
export NMTVR=_NMTVR_
#
export nsout=_NSOUT_
export lsm-_LSM_
#
#   Control for post and time averaging  If "YES" then run
#   -- Defaults to "NO" 
#
 export gfsio_in=_GFSIO_IN_
 export gfsio_out=_GFSIO_OUT_
#
 export DYNVARS=_DYNVARS_
 export PHYVARS=_PHYVARS_

 export TRACERVARS=_TRACEVARS_
#
export NGPTC=${NGPTC:-$((wave/10))}
export LEVR=_LEVR_
#
#     Forecaset script and executable name
#
 export FCSTSCRIPT=_FCSTSCRIPT_
 export FCSTEXEC=_FCSTEXEC_
#
#
# ***************************************************************
#    Below here no change needed most of the time
#    ____________________________________________
#
cp $FILE configure_file
cp configure_file $RUNDIR
mkdir -p $RUNDIR
cd $RUNDIR
 export COMOUT=$RUNDIR
#
 export FIXGLOBAL=_FIXGLOBAL_
 export FIX_RAD=_FIX_RAD_
#
 export POSTGPDIR=_POSTGPDIR_
 export POSTGPEXEC=_POSTGPEXEC_
 export POSTGPSH=_POSTGPSH_
#
 export LANDICE_OPT=_LANDICE_OPT_
 export CLIMO_FIELDS_OPT=_CLIMO_FIELDS_OPT_
#
if [[ $wave -eq 62 ]] ; then
  export LONF=192 ; export LATG=94 ; export LONR=192 ; export LATR=94
  export im=$LONR ; export jm=$LATR ; export iop=144 ; export jop=73
  if [[ $lm -eq 64 ]] ; then
    export DELTIM=${DELTIM:-900}
  fi
  if [[ $lm -eq 150 ]] ; then
    export DELTIM=${DELTIM:-180}
  fi
  export DELTIM=${DELTIM:-1200}
elif [[ $wave -eq 126 ]] ; then
  export LONF=384 ; export LATG=190 ; export LONR=384 ; export LATR=190
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-600}
elif [[ $wave -eq 170 ]] ; then
  export LONF=512 ; export LATG=256 ; export LONR=512 ; export LATR=256
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-450}
elif [[ $wave -eq 190 ]] ; then
  export LONF=576 ; export LATG=288 ; export LONR=576 ; export LATR=288
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-300}
elif [[ $wave -eq 254 ]] ; then
  export LONF=768 ; export LATG=384 ; export LONR=768 ; export LATR=384
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-300}
elif [[ $wave -eq 382 ]] ; then
  export LONF=1152 ; export LATG=576 ; export LONR=1152 ; export LATR=576
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-180}
elif [[ $wave -eq 510 ]] ; then
  export LONF=1536 ; export LATG=766 ; export LONR=1536 ; export LATR=766
  export im=$LONR ; export jm=$LATR ; export iop=360 ; export jop=181
  export DELTIM=${DELTIM:-120}
  export OROGRAPHY=$TOPDIR/wx23ys/fix.all/global_orography.t${wave}.grb
  export MTNVAR=$TOPDIR/wx23my/fix.all/global_mtnvar.t${wave}.f77
fi
#
# ------------------------ initial condition ----------------
#
  export JCAP=$wave
  export LEVS=$lm
  export LONB=$im
  export LATB=$jm
  export VERBOSE=YES
#
  export SIGI=$RUNDIR/gfsanl.$CDATE
  export SFCI=$RUNDIR/sfcanl.$CDATE
  export FHINI=_FHINI_
#
# ---------------------------------------- fcst ----------------------
#
if [[ $nhourb -lt $nhours ]] ; then

  export FNTSFA=
  export FNACNA=
#
  export FHOUT=$fout
  export FHZER=$fzer
  export FHCYC=$fcyc
  export FHDFI=$fdfi
  export FHLWR=${FHLWR:-3}
  export FHSWR=${FHSWR:-1}
  export FHMAX=$nhours
  export FHRES=${FHRES:-$FHMAX}
  export FHROT=${FHROT:-0}
#
  $FCSTSCRIPT || exit
fi
#
