#!/bin/ksh
#
#@ output = _OUTPUT_
#@ error = _ERROR_
#@ job_type = _JOB_TYPE_
#@ tasks_per_node = _TASK_PER_NODE_
#@ node = _NODES_
#@ node_usage=_NODE_USAGE_
#@ resources=ConsumableCPUs(1)ConsumableMemory(_CONSUMABLE_MEMORY_)
#@ class = _CLASS_
#@ wall_clock_limit = _WALL_CLOCK_TIME_
#@ preferences = Feature == "dev"
#@ network.MPI = csss,shared,us
#@ bulkxfer=yes
#@ account_no=_ACCT_NO_
#@ queue
#
#
set -x
#
### For MPI
#
export BIND_TASKS=no
export MP_EAGER_LIMIT=65536
export MP_SHARED_MEMORY=yes
export MP_SINGLE_THREAD=_MP_SINGLE_THREAD_
export MP_LABELIO=yes
export MP_STDOUTMODE=ordered
export MEMORY_AFFINITY=mcm
export MP_COREFILE_FORMAT=core.txt
export TARGET_CPU_RANGE="-1"
export XLSMPOPTS="parthds=_THREADS_:stack=128000000"
export AIXTHREAD_SCOPE=S

RUNDIR=_RUNDIR_
DATADIR=_DATADIR_
SRCDIR=_SRCDIR_

mkdir -p $RUNDIR
cd $RUNDIR

rm -f $RUNDIR/*

cp $DATADIR/_MAIN_INPUT_FILENAME_ _main_input_file_
cp _CONFIG_FILE_ configure_file
_BOCO_
cp _RRT_/tr* .

cp _ETA_ ETAMPNEW_DATA
cp _RRT_/RRT* .
cp _TBL_/*.TBL .

echo "Model started:  " `date`

poe hpmcount -o _TIMING_FILE_ _HYBRID_LAUNCH_ _EXEDIR_/NMM_NEMS.x
echo "Model ended:    " `date`

exit

