!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!       Local arrays referencing the Import/Export states
!       -------------------------------------------------
        real, pointer, dimension(:,:)   :: RnEM ! EXPORT: Rn Emission         
        real, pointer, dimension(:,:)   :: RnLS ! EXPORT: Rn Decay         
        real, pointer, dimension(:,:)   :: RnSC ! EXPORT: Rn Surface Concentration         
        real, pointer, dimension(:,:)   :: RnCL ! EXPORT: Rn Column Burden         
