!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!     Bin sizes
!     ---------

!     Bin-indexed Chem Arrays
!     -----------------------

!     Local array referencing the Import/Export states
!     ------------------------------------------------
      type(Chem_Array), target        ::    CFC12S ! EXPORT: Stratospheric CFC-12 (CCl2F2)
      type(Chem_Array), pointer       :: ptrCFC12S ! EXPORT: Stratospheric CFC-12 (CCl2F2)
      type(Chem_Array), target        ::    CFC12T ! EXPORT: Tropospheric CFC-12 (CCl2F2)
      type(Chem_Array), pointer       :: ptrCFC12T ! EXPORT: Tropospheric CFC-12 (CCl2F2)
      type(Chem_Array), target        ::    CFC12EM ! EXPORT: CFC-12 Emission
      type(Chem_Array), pointer       :: ptrCFC12EM ! EXPORT: CFC-12 Emission
      type(Chem_Array), target        ::    CFC12SLS ! EXPORT: Stratospheric CFC-12 Loss
      type(Chem_Array), pointer       :: ptrCFC12SLS ! EXPORT: Stratospheric CFC-12 Loss
      type(Chem_Array), target        ::    CFC12TLS ! EXPORT: Tropospheric CFC-12 Loss
      type(Chem_Array), pointer       :: ptrCFC12TLS ! EXPORT: Tropospheric CFC-12 Loss
      type(Chem_Array), target        ::    CFC12SCL ! EXPORT: Stratospheric CFC-12 Column
      type(Chem_Array), pointer       :: ptrCFC12SCL ! EXPORT: Stratospheric CFC-12 Column
      type(Chem_Array), target        ::    CFC12TCL ! EXPORT: Tropospheric CFC-12 Column
      type(Chem_Array), pointer       :: ptrCFC12TCL ! EXPORT: Tropospheric CFC-12 Column
