#!/bin/ksh
#
#@ output = out
#@ error = err
#@ job_type = parallel
#@ tasks_per_node = 16
#@ node = 3
#@ node_usage=not_shared
####@ blocking = unlimited
#@ resources=ConsumableCPUs(1)ConsumableMemory(500MB)
##@ class = debug
#@ class = dev
###@ group = devqpri
###@ group = devonprod
#@ wall_clock_limit = 02:30:00
##@ wall_clock_limit = 00:10:00
#@ preferences = Feature == "dev"
#@ network.MPI = csss,shared,us
#@ bulkxfer=yes
#@ account_no=NAM-T2O
#@ queue
#
#
set -x
#
### For MPI
#
export BIND_TASKS=yes
export MP_EAGER_LIMIT=65536
export MP_SHARED_MEMORY=yes
export MP_SINGLE_THREAD=yes
export MP_LABELIO=yes
export MP_STDOUTMODE=ordered
export MEMORY_AFFINITY=mcm
export MP_COREFILE_FORMAT=core.txt
export TARGET_CPU_RANGE="-1"
export XLSMPOPTS="parthds=1:stack=128000000"
export AIXTHREAD_SCOPE=S


RUNDIR=/ptmp/${USER}/nmm_regional.3 ### change here
DATADIR=/meso/noscrub/wx22tb/nmmb_input/input_regional/2008052700
SRCDIR=/meso/save/${USER}/NEW_STRUCTURE_A   ##### change here

mkdir -p $RUNDIR
cd $RUNDIR
ls

echo $DATADIR
ls $DATADIR

cp $DATADIR/test_input_nmmb_regional.d01 main_input_filename
cp $DATADIR/boco* . 
cp $SRCDIR/exp/configure_files/configfile_regional_new $RUNDIR/configure_file

cp $DATADIR/tr* .

cp /nwprod/fix/nam_micro_lookup.dat ETAMPNEW_DATA
cp /meso/save/wx22tb/WRF_repository/run/RRT* .
cp /meso/noscrub/wx20rv/NOAH_wrf_data/*.TBL .

echo "Model started:  " `date`

poe  hpmcount -o nmm.3.regional_test /u/wx15ja/bin/hybrid_launch $SRCDIR/exe/NMM_NEMS.x

echo "Model ended:    " `date`

exit

