#!/bin/ksh
#
#@ output = out
#@ error = err
#@ job_type = parallel
# @ parallel_threads = 1
# @ task_affinity = cpu(1)
# @ blocking = unlimited
# @ node_usage = shared
#@ total_tasks = 32
#@ resources=ConsumableCPUs(1)ConsumableMemory(3500MB)
#@ class = dev
#@ wall_clock_limit = 04:00:00
#@ preferences = Feature == "dev"
#@ network.MPI = sn_all,shared,us
#@ account_no=NAM-T2O
#@ queue
#
#
set -x
#
### For MPI
#
export BIND_TASKS=yes
export MP_EAGER_LIMIT=65536
export MP_SHARED_MEMORY=yes
export MP_SINGLE_THREAD=yes
export TARGET_CPU_RANGE=-1
export OMP_MAX_THREADS=1
export MP_LABELIO=yes
export MP_STDOUTMODE=ordered
export MP_COREFILE_FORMAT=core.txt
export TARGET_CPU_RANGE="-1"
export XLSMPOPTS=parthds=1:spins=0:yields=0:stack=128000000:schedule=static
export AIXTHREAD_SCOPE=S




RUNDIR=/ptmp/${USER}/nmm.regional.x ### change here
DATADIR=/ptmp/${USER}/nmmb_init_regional
SRCDIR=/meso/save/${USER}/trunk   ##### change here

mkdir -p $RUNDIR
cd $RUNDIR
ls

echo $DATADIR
ls $DATADIR

cp $DATADIR/test_input_umo_regional.nemsio.d01 main_input_filename_nemsio
cp $DATADIR/boco* . 
cp $SRCDIR/job/configfile_regional_new configure_file

cp $DATADIR/tr* .

cp /nwprod/fix/nam_micro_lookup.dat ETAMPNEW_DATA
cp /meso/save/wx22tb/WRF_repository/run/RRT* .
cp /meso/noscrub/wx20rv/NOAH_wrf_data/*.TBL .

################ GFS physics part ######################
#
cp /meso/noscrub/wx20rv/GFS_phys_data/atm_namelist .
cp /meso/noscrub/wx20rv/GFS_phys_data/GWD.bin .

ln -sf /nwprod/fix/global_o3prdlos.f77 fort.28
ln -sf /nwprod/fix/global_o3clim.txt fort.48
#
########################################################

echo "Model started:  " `date`

poe hpmcount -o nmm.regional_test $SRCDIR/exe/NMM_NEMS.x

echo "Model ended:    " `date`

exit

