!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!     Bin sizes
!     ---------
      integer, parameter              :: NBIN_O3CM = 2 ! Total ozone 

!     Bin-indexed Chem Arrays
!     -----------------------
      type(Chem_Array), target        ::    O3CM(NBIN_O3CM) ! EXPORT: Total ozone 
      type(Chem_Array), pointer       :: ptrO3CM(:)  ! EXPORT: Total ozone 

!     Local array referencing the Import/Export states
!     ------------------------------------------------
      type(Chem_Array), target        ::    O3 ! EXPORT: Ozone from GOCART
      type(Chem_Array), pointer       :: ptrO3 ! EXPORT: Ozone from GOCART
      type(Chem_Array), target        ::    O3PPMV ! EXPORT: Ozone from GOCART
      type(Chem_Array), pointer       :: ptrO3PPMV ! EXPORT: Ozone from GOCART
