!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


      ptrO3 => O3   ! Ozone from GOCART
      call MAPL_GetPointer ( EXPORT, O3%data3d,  'O3', RC=STATUS )
      VERIFY_(STATUS)

      ptrO3PPMV => O3PPMV   ! Ozone from GOCART
      call MAPL_GetPointer ( EXPORT, O3PPMV%data3d,  'O3PPMV', RC=STATUS )
      VERIFY_(STATUS)

      ptrO3CM => O3CM   ! Total ozone Bin 001
      call MAPL_GetPointer ( EXPORT, O3CM(1)%data2d,  'O3CM001', RC=STATUS )
      VERIFY_(STATUS)
      call MAPL_GetPointer ( EXPORT, O3CM(2)%data2d,  'O3CM002', RC=STATUS )
      VERIFY_(STATUS)
