#!/bin/ksh

export CC=xlc
MAKEDEP=`pwd`
echo ${MAKEDEP}
PREFIX=${MAKEDEP}/util/makedepf90-2.8.8
DIR=${MAKEDEP}
MANDIR=${PREFIX} 
${MAKEDEP}/configure --prefix=${PREFIX} --bindir=${DIR} --mandir=${MANDIR}
gmake -f Makefile 
gmake -f Makefile install
echo "done."
exit
