!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!       Local arrays referencing the Import/Export states
!       -------------------------------------------------
        real, pointer, dimension(:,:)   :: COEM ! EXPORT: CO Emission         
        real, pointer, dimension(:,:)   :: COPD ! EXPORT: CO Chemical Production         
        real, pointer, dimension(:,:)   :: COLS ! EXPORT: CO Chemical Loss         
        real, pointer, dimension(:,:)   :: COSC ! EXPORT: CO Surface Concentration         
        real, pointer, dimension(:,:)   :: COCL ! EXPORT: CO Column Burden         
