!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!     Bin sizes
!     ---------
      integer, parameter              :: NBIN_SUWT = 4 ! Sulfate Wet Deposition 
      integer, parameter              :: NBIN_SUEM = 4 ! Sulfate Emission 
      integer, parameter              :: NBIN_SUDP = 4 ! Sulfate Dry Deposition 

!     Bin-indexed Chem Arrays
!     -----------------------
      type(Chem_Array), target        ::    SUWT(NBIN_SUWT) ! EXPORT: Sulfate Wet Deposition 
      type(Chem_Array), pointer       :: ptrSUWT(:)  ! EXPORT: Sulfate Wet Deposition 
      type(Chem_Array), target        ::    SUEM(NBIN_SUEM) ! EXPORT: Sulfate Emission 
      type(Chem_Array), pointer       :: ptrSUEM(:)  ! EXPORT: Sulfate Emission 
      type(Chem_Array), target        ::    SUDP(NBIN_SUDP) ! EXPORT: Sulfate Dry Deposition 
      type(Chem_Array), pointer       :: ptrSUDP(:)  ! EXPORT: Sulfate Dry Deposition 

!     Local array referencing the Import/Export states
!     ------------------------------------------------
      type(Chem_Array), target        ::    PSO2 ! EXPORT: SO2 Prod from DMS oxidation
      type(Chem_Array), pointer       :: ptrPSO2 ! EXPORT: SO2 Prod from DMS oxidation
      type(Chem_Array), target        ::    PMSA ! EXPORT: MSA Prod from DMS oxidation
      type(Chem_Array), pointer       :: ptrPMSA ! EXPORT: MSA Prod from DMS oxidation
      type(Chem_Array), target        ::    PSO4g ! EXPORT: SO4 Prod from SO2 oxidation
      type(Chem_Array), pointer       :: ptrPSO4g ! EXPORT: SO4 Prod from SO2 oxidation
      type(Chem_Array), target        ::    PSO4wet ! EXPORT: SO4 Prod from wet SO2 oxidation
      type(Chem_Array), pointer       :: ptrPSO4wet ! EXPORT: SO4 Prod from wet SO2 oxidation
      type(Chem_Array), target        ::    PSO4aq ! EXPORT: SO4 Prod from aqueous SO2 oxidation
      type(Chem_Array), pointer       :: ptrPSO4aq ! EXPORT: SO4 Prod from aqueous SO2 oxidation
      type(Chem_Array), target        ::    SO4MASS ! EXPORT: SO4 Aerosol Mass Concentration
      type(Chem_Array), pointer       :: ptrSO4MASS ! EXPORT: SO4 Aerosol Mass Concentration
      type(Chem_Array), target        ::    SO2SMASS ! EXPORT: SO2 Surface Mass Concentration
      type(Chem_Array), pointer       :: ptrSO2SMASS ! EXPORT: SO2 Surface Mass Concentration
      type(Chem_Array), target        ::    SO2CMASS ! EXPORT: SO2 Column Mass Density
      type(Chem_Array), pointer       :: ptrSO2CMASS ! EXPORT: SO2 Column Mass Density
      type(Chem_Array), target        ::    SO4SMASS ! EXPORT: SO4 Surface Mass Concentration
      type(Chem_Array), pointer       :: ptrSO4SMASS ! EXPORT: SO4 Surface Mass Concentration
      type(Chem_Array), target        ::    SO4CMASS ! EXPORT: SO4 Column Mass Density
      type(Chem_Array), pointer       :: ptrSO4CMASS ! EXPORT: SO4 Column Mass Density
      type(Chem_Array), target        ::    DMSSMASS ! EXPORT: DMS Surface Mass Concentration
      type(Chem_Array), pointer       :: ptrDMSSMASS ! EXPORT: DMS Surface Mass Concentration
      type(Chem_Array), target        ::    DMSCMASS ! EXPORT: DMS Column Mass Density
      type(Chem_Array), pointer       :: ptrDMSCMASS ! EXPORT: DMS Column Mass Density
      type(Chem_Array), target        ::    SUPSO2 ! EXPORT: SO2 Prod from DMS Oxidation [column]
      type(Chem_Array), pointer       :: ptrSUPSO2 ! EXPORT: SO2 Prod from DMS Oxidation [column]
      type(Chem_Array), target        ::    SUPSO4g ! EXPORT: SO4 Prod from Gaseous SO2 Oxidation [column]
      type(Chem_Array), pointer       :: ptrSUPSO4g ! EXPORT: SO4 Prod from Gaseous SO2 Oxidation [column]
      type(Chem_Array), target        ::    SUPSO4aq ! EXPORT: SO4 Prod from Aqueous SO2 Oxidation [column]
      type(Chem_Array), pointer       :: ptrSUPSO4aq ! EXPORT: SO4 Prod from Aqueous SO2 Oxidation [column]
      type(Chem_Array), target        ::    SUPSO4wt ! EXPORT: SO4 Prod from Aqueous SO2 Oxidation (wet dep) [column]
      type(Chem_Array), pointer       :: ptrSUPSO4wt ! EXPORT: SO4 Prod from Aqueous SO2 Oxidation (wet dep) [column]
      type(Chem_Array), target        ::    SO4EMAN ! EXPORT: SO4 Anthropogenic Emissions
      type(Chem_Array), pointer       :: ptrSO4EMAN ! EXPORT: SO4 Anthropogenic Emissions
      type(Chem_Array), target        ::    SO2EMAN ! EXPORT: SO2 Anthropogenic Emissions
      type(Chem_Array), pointer       :: ptrSO2EMAN ! EXPORT: SO2 Anthropogenic Emissions
      type(Chem_Array), target        ::    SO2EMBB ! EXPORT: SO2 Biomass Burning Emissions
      type(Chem_Array), pointer       :: ptrSO2EMBB ! EXPORT: SO2 Biomass Burning Emissions
      type(Chem_Array), target        ::    SO2EMVN ! EXPORT: SO2 Volcanic (non-explosive) Emissions
      type(Chem_Array), pointer       :: ptrSO2EMVN ! EXPORT: SO2 Volcanic (non-explosive) Emissions
      type(Chem_Array), target        ::    SO2EMVE ! EXPORT: SO2 Volcanic (explosive) Emissions
      type(Chem_Array), pointer       :: ptrSO2EMVE ! EXPORT: SO2 Volcanic (explosive) Emissions
      type(Chem_Array), target        ::    SUPMSA ! EXPORT: MSA Prod from DMS Oxidation [column]
      type(Chem_Array), pointer       :: ptrSUPMSA ! EXPORT: MSA Prod from DMS Oxidation [column]
      type(Chem_Array), target        ::    SUEXTTAU ! EXPORT: SO4 Extinction AOT [550 nm]
      type(Chem_Array), pointer       :: ptrSUEXTTAU ! EXPORT: SO4 Extinction AOT [550 nm]
      type(Chem_Array), target        ::    SUSCATAU ! EXPORT: SO4 Scattering AOT [550 nm]
      type(Chem_Array), pointer       :: ptrSUSCATAU ! EXPORT: SO4 Scattering AOT [550 nm]
