      MODULE module_FIM_INTERNAL_STATE

      USE ESMF_MOD

      IMPLICIT NONE

      PRIVATE
      PUBLIC :: FIM_INTERNAL_STATE,WRAP_FIM_INTERNAL_STATE

      TYPE FIM_INTERNAL_STATE

        integer i

      END TYPE FIM_INTERNAL_STATE

      TYPE WRAP_FIM_INTERNAL_STATE
        TYPE(FIM_INTERNAL_STATE),POINTER :: FIM_INT_STATE
      END TYPE WRAP_FIM_INTERNAL_STATE

      END MODULE module_FIM_INTERNAL_STATE

