!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!     Bin sizes
!     ---------
      integer, parameter              :: NBIN_SSEM = 5 ! Sea Salt Emission 
      integer, parameter              :: NBIN_SSWT = 5 ! Sea Salt Wet Deposition 
      integer, parameter              :: NBIN_SSSD = 5 ! Sea Salt Sedimentation 
      integer, parameter              :: NBIN_SSDP = 5 ! Sea Salt Dry Deposition 

!     Bin-indexed Chem Arrays
!     -----------------------
      type(Chem_Array), target        ::    SSEM(NBIN_SSEM) ! EXPORT: Sea Salt Emission 
      type(Chem_Array), pointer       :: ptrSSEM(:)  ! EXPORT: Sea Salt Emission 
      type(Chem_Array), target        ::    SSWT(NBIN_SSWT) ! EXPORT: Sea Salt Wet Deposition 
      type(Chem_Array), pointer       :: ptrSSWT(:)  ! EXPORT: Sea Salt Wet Deposition 
      type(Chem_Array), target        ::    SSSD(NBIN_SSSD) ! EXPORT: Sea Salt Sedimentation 
      type(Chem_Array), pointer       :: ptrSSSD(:)  ! EXPORT: Sea Salt Sedimentation 
      type(Chem_Array), target        ::    SSDP(NBIN_SSDP) ! EXPORT: Sea Salt Dry Deposition 
      type(Chem_Array), pointer       :: ptrSSDP(:)  ! EXPORT: Sea Salt Dry Deposition 

!     Local array referencing the Import/Export states
!     ------------------------------------------------
      type(Chem_Array), target        ::    SSMASS ! EXPORT: Sea Salt Mass Mixing Ratio
      type(Chem_Array), pointer       :: ptrSSMASS ! EXPORT: Sea Salt Mass Mixing Ratio
      type(Chem_Array), target        ::    SSMASS25 ! EXPORT: Sea Salt Mass Mixing Ratio - PM 2.5
      type(Chem_Array), pointer       :: ptrSSMASS25 ! EXPORT: Sea Salt Mass Mixing Ratio - PM 2.5
      type(Chem_Array), target        ::    SSSMASS ! EXPORT: Sea Salt Surface Mass Concentration
      type(Chem_Array), pointer       :: ptrSSSMASS ! EXPORT: Sea Salt Surface Mass Concentration
      type(Chem_Array), target        ::    SSCMASS ! EXPORT: Sea Salt Column Mass Density
      type(Chem_Array), pointer       :: ptrSSCMASS ! EXPORT: Sea Salt Column Mass Density
      type(Chem_Array), target        ::    SSEXTTAU ! EXPORT: Sea Salt Extinction AOT [550 nm]
      type(Chem_Array), pointer       :: ptrSSEXTTAU ! EXPORT: Sea Salt Extinction AOT [550 nm]
      type(Chem_Array), target        ::    SSSCATAU ! EXPORT: Sea Salt Scattering AOT [550 nm]
      type(Chem_Array), pointer       :: ptrSSSCATAU ! EXPORT: Sea Salt Scattering AOT [550 nm]
      type(Chem_Array), target        ::    SSSMASS25 ! EXPORT: Sea Salt Surface Mass Concentration - PM 2.5
      type(Chem_Array), pointer       :: ptrSSSMASS25 ! EXPORT: Sea Salt Surface Mass Concentration - PM 2.5
      type(Chem_Array), target        ::    SSCMASS25 ! EXPORT: Sea Salt Column Mass Density - PM 2.5
      type(Chem_Array), pointer       :: ptrSSCMASS25 ! EXPORT: Sea Salt Column Mass Density - PM 2.5
      type(Chem_Array), target        ::    SSEXTT25 ! EXPORT: Sea Salt Extinction AOT [550 nm] - PM 2.5
      type(Chem_Array), pointer       :: ptrSSEXTT25 ! EXPORT: Sea Salt Extinction AOT [550 nm] - PM 2.5
      type(Chem_Array), target        ::    SSSCAT25 ! EXPORT: Sea Salt Scattering AOT [550 nm] - PM 2.5
      type(Chem_Array), pointer       :: ptrSSSCAT25 ! EXPORT: Sea Salt Scattering AOT [550 nm] - PM 2.5
      type(Chem_Array), target        ::    SSAERIDX ! EXPORT: Sea Salt TOMS UV Aerosol Index
      type(Chem_Array), pointer       :: ptrSSAERIDX ! EXPORT: Sea Salt TOMS UV Aerosol Index
