#!/bin/ksh
#
#@ output = nmm_out/out
#@ error = nmm_out/err
#@ job_type = parallel
###@ total_tasks = 32
#@ tasks_per_node = 16
##@ tasks_per_node = 6
##@ node = 1
#@ node = 1
#@ node_usage=not_shared
####@ blocking = unlimited
#@ resources=ConsumableCPUs(1)ConsumableMemory(500MB)
##@ class = debug
#@ class = dev
###@ group = devqpri
###@ group = devonprod
#@ wall_clock_limit = 01:45:00
###@ wall_clock_limit = 00:40:00
##@ wall_clock_limit = 00:10:00
#@ preferences = Feature == "dev"
#@ network.MPI = csss,shared,us
#@ bulkxfer=yes
#@ account_no=NAM-T2O
#@ queue
#
#
set -x
#
### For MPI
#
export BIND_TASKS=yes
export MP_EAGER_LIMIT=65536
export MP_SHARED_MEMORY=yes
export MP_SINGLE_THREAD=yes
export MP_LABELIO=yes
export MP_STDOUTMODE=ordered
export MEMORY_AFFINITY=mcm
export MP_COREFILE_FORMAT=core.txt
export TARGET_CPU_RANGE="-1"
export XLSMPOPTS="parthds=1:stack=128000000"
export AIXTHREAD_SCOPE=S


RUNDIR=/ptmp/${USER}/nmm.1 ### change here
DATADIR=/meso/noscrub/wx22tb/nmmb_input/input_global
SRCDIR=/meso/save/${USER}/trunk   ##### change here

mkdir -p $RUNDIR
cd $RUNDIR
ls

echo $DATADIR
ls $DATADIR

cp $DATADIR/test_input_nmmb_global_257_181_35-2007091800 main_input_filename
cp $SRCDIR/run/configfile_global_new $RUNDIR/configure_file

cp /meso/save/wx22tb/co2/co2.60_hyb_opnl.levels_2mbtop co2_trans
cp $DATADIR/co2.35_hybrid_50mbtop co2_trans
cp $DATADIR/tr* .

cp /nwprod/fix/nam_micro_lookup.dat ETAMPNEW_DATA
cp /meso/save/wx22tb/WRF_repository/run/RRT* .
cp /meso/noscrub/wx20rv/NOAH_wrf_data/*.TBL .
cp /meso/noscrub/wx20rv/NOAH_wrf_data/grib* .
#ln -sf loopdata fort.98

#ln -sf /gpfstmp/wx22tb/run_umo_serial/global_sums fort.58
#ln -sf /stmp/wx22tb/run_umo_serial/global_sums fort.58

poe $SRCDIR/MAIN_NEMS.x

exit

