!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


!     Bin sizes
!     ---------
      integer, parameter              :: NBIN_OCWT = 2 ! Organic Carbon Wet Deposition 
      integer, parameter              :: NBIN_OCDP = 2 ! Organic Carbon Dry Deposition 
      integer, parameter              :: NBIN_OCEM = 2 ! Organic Carbon Emission 

!     Bin-indexed Chem Arrays
!     -----------------------
      type(Chem_Array), target        ::    OCWT(NBIN_OCWT) ! EXPORT: Organic Carbon Wet Deposition 
      type(Chem_Array), pointer       :: ptrOCWT(:)  ! EXPORT: Organic Carbon Wet Deposition 
      type(Chem_Array), target        ::    OCDP(NBIN_OCDP) ! EXPORT: Organic Carbon Dry Deposition 
      type(Chem_Array), pointer       :: ptrOCDP(:)  ! EXPORT: Organic Carbon Dry Deposition 
      type(Chem_Array), target        ::    OCEM(NBIN_OCEM) ! EXPORT: Organic Carbon Emission 
      type(Chem_Array), pointer       :: ptrOCEM(:)  ! EXPORT: Organic Carbon Emission 

!     Local array referencing the Import/Export states
!     ------------------------------------------------
      type(Chem_Array), target        ::    OCMASS ! EXPORT: Organic Carbon Mass Mixing Ratio 
      type(Chem_Array), pointer       :: ptrOCMASS ! EXPORT: Organic Carbon Mass Mixing Ratio 
      type(Chem_Array), target        ::    OCHYPHIL ! EXPORT: Organic Carbon Hydrophobic to Hydrophilic 
      type(Chem_Array), pointer       :: ptrOCHYPHIL ! EXPORT: Organic Carbon Hydrophobic to Hydrophilic 
      type(Chem_Array), target        ::    OCEMAN ! EXPORT: Organic Carbon Anthropogenic Emissions 
      type(Chem_Array), pointer       :: ptrOCEMAN ! EXPORT: Organic Carbon Anthropogenic Emissions 
      type(Chem_Array), target        ::    OCEMBB ! EXPORT: Organic Carbon Biomass Burning Emissions 
      type(Chem_Array), pointer       :: ptrOCEMBB ! EXPORT: Organic Carbon Biomass Burning Emissions 
      type(Chem_Array), target        ::    OCEMBF ! EXPORT: Organic Carbon Biofuel Emissions 
      type(Chem_Array), pointer       :: ptrOCEMBF ! EXPORT: Organic Carbon Biofuel Emissions 
      type(Chem_Array), target        ::    OCEMBG ! EXPORT: Organic Carbon Biogenic Emissions 
      type(Chem_Array), pointer       :: ptrOCEMBG ! EXPORT: Organic Carbon Biogenic Emissions 
      type(Chem_Array), target        ::    OCSMASS ! EXPORT: Organic Carbon Surface Mass Concentration 
      type(Chem_Array), pointer       :: ptrOCSMASS ! EXPORT: Organic Carbon Surface Mass Concentration 
      type(Chem_Array), target        ::    OCCMASS ! EXPORT: Organic Carbon Column Mass Density 
      type(Chem_Array), pointer       :: ptrOCCMASS ! EXPORT: Organic Carbon Column Mass Density 
      type(Chem_Array), target        ::    OCEXTTAU ! EXPORT: Organic Carbon Extinction AOT [550 nm] 
      type(Chem_Array), pointer       :: ptrOCEXTTAU ! EXPORT: Organic Carbon Extinction AOT [550 nm] 
      type(Chem_Array), target        ::    OCSCATAU ! EXPORT: Organic Carbon Scattering AOT [550 nm] 
      type(Chem_Array), pointer       :: ptrOCSCATAU ! EXPORT: Organic Carbon Scattering AOT [550 nm] 
