#!/bin/ksh
set -x

if [[ $1 = 3 ]]; then
     cp conf/configure.nems.AIX_ESMF_3 conf/configure.nems
     cp ESMFVersionDefine_ESMF_3.h ESMFVersionDefine.h
     echo "Use the ESMF 3.1.0rp2 library"
elif [[ $1 = 3_zeus ]]; then
     cp conf/configure.nems.Zeus.intel conf/configure.nems
     cp ESMFVersionDefine_ESMF_3.h ESMFVersionDefine.h
     echo "Use the ESMF 3.1.0rp2 library"
elif [[ $1 = 3_wcoss ]]; then
     cp conf/configure.nems.Wcoss.intel conf/configure.nems
     cp ESMFVersionDefine_ESMF_3.h ESMFVersionDefine.h
     echo "Use the ESMF 3.1.0rp2 library"
elif [[ $1 = 4 ]]; then
     cp conf/configure.nems.AIX_ESMF_4 conf/configure.nems
     cp ESMFVersionDefine_ESMF_4.h ESMFVersionDefine.h
     echo "Use the ESMF 4.0.0rp2 library"
elif [[ $1 = 5 ]]; then
     cp conf/configure.nems.AIX_ESMF_5 conf/configure.nems
     cp ESMFVersionDefine_ESMF_5.h ESMFVersionDefine.h
     echo "Use the ESMF 5.1.0 library"
elif [[ $1 = 5.2 ]]; then
     cp conf/configure.nems.AIX_ESMF_520rp1 conf/configure.nems
     cp ESMFVersionDefine_ESMF_520rp1.h ESMFVersionDefine.h
     echo "Use the ESMF 5.2.0rp1 library"
elif [[ $1 = traps_on ]]; then
     cp conf/configure.nems.AIX_TRAPS_ON conf/configure.nems
     cp ESMFVersionDefine_ESMF_3.h ESMFVersionDefine.h
     echo "Use the ESMF 3.1.0rp2 library"
elif [[ $1 = 5.2_wcoss ]]; then
     cp conf/configure.nems.Wcoss.intel_ESMF_520rp1 conf/configure.nems
     cp ESMFVersionDefine_ESMF_520rp1.h ESMFVersionDefine.h
     echo "Use the ESMF 5.2.0rp1 library"
elif [[ $1 = 5.2_zeus ]]; then
     cp conf/configure.nems.Zeus.intel_ESMF_520rp1 conf/configure.nems
     cp ESMFVersionDefine_ESMF_520rp1.h ESMFVersionDefine.h
     echo "Use the ESMF 5.2.0rp1 library"
elif [[ $1 = 5.3_zeus ]]; then
     cp conf/configure.nems.Zeus.intel_ESMF_530 conf/configure.nems
     cp ESMFVersionDefine_ESMF_520rp1.h ESMFVersionDefine.h
     echo "Use the ESMF 5.3.0 library"
elif [[ $1 = 6.1_zeus ]]; then
     cp conf/configure.nems.Zeus.intel_ESMF_610 conf/configure.nems
     cp ESMFVersionDefine_ESMF_520rp1.h ESMFVersionDefine.h
     echo "Use the ESMF 6.1.0 library"
elif [[ $1 = 6.1.1_zeus ]]; then
     cp conf/configure.nems.Zeus.intel_ESMF_611 conf/configure.nems
     cp ESMFVersionDefine_ESMF_520rp1.h ESMFVersionDefine.h
     echo "Use the ESMF 6.1.1 library"
else
     echo;echo "     Run ./esmf_version with one argument:"
     echo "When using the ESMF 3.1.0rp2 library on the CCS   machine, enter 'esmf_version 3'"
     echo "When using the ESMF 3.1.0rp2 library on the ZEUS  machine, enter 'esmf_version 3_zeus'"
     echo "When using the ESMF 3.1.0rp2 library on the WCOSS machine, enter 'esmf_version 3_wcoss'"
     echo "When using the ESMF 3.1.0rp2 library and turn on traps,   enter 'esmf_version traps_on'"
     echo "When using the ESMF 4.0.0rp2 library on the CCS   machine, enter 'esmf_version 4'"
     echo "When using the ESMF 5.1.0    library on the CCS   machine, enter 'esmf_version 5'"
     echo "When using the ESMF 5.2.0rp1 library on the CCS   machine, enter 'esmf_version 5.2'"
     echo "When using the ESMF 5.2.0rp1 library on the ZEUS   machine, enter 'esmf_version 5.2_zeus'"
     echo "When using the ESMF 5.2.0rp1 library on the WCOSS machine, enter 'esmf_version 5.2_wcoss'"
     echo "When using the ESMF 5.3.0 library on the ZEUS   machine, enter 'esmf_version 5.3_zeus'"
     echo "When using the ESMF 6.1.0 library on the ZEUS   machine, enter 'esmf_version 6.1_zeus'"
     echo "When using the ESMF 6.1.1 library on the ZEUS   machine, enter 'esmf_version 6.1.1_zeus'"
fi     
