#!/bin/sh

if [[ $1 = 3 ]]; then
     cp conf/configure.nems.AIX_ESMF_3 conf/configure.nems
     cp ESMFVersionDefine_ESMF_3.h ESMFVersionDefine.h
     print "Use the ESMF 3.1.0rp2 library"
elif [[ $1 = 4 ]]; then
     cp conf/configure.nems.AIX_ESMF_4 conf/configure.nems
     cp ESMFVersionDefine_ESMF_4.h ESMFVersionDefine.h
     print "Use the ESMF 4.0.0rp2 library"
elif [[ $1 = 5 ]]; then
     cp conf/configure.nems.AIX_ESMF_5 conf/configure.nems
     cp ESMFVersionDefine_ESMF_5.h ESMFVersionDefine.h
     print "Use the ESMF 5.1.0 library"
else
     print "When using the ESMF 3.1.0rp2 library, enter 'esmf_version 3'."
     print "When using the ESMF 4.0.0rp2 library, enter 'esmf_version 4'."
     print "When using the ESMF 5.1.0 library, enter 'esmf_version 5'."
fi     
